[workspace]
channels = ["conda-forge"]
name = "view-mask"
platforms = ["win-64", "osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"

[pypi-dependencies]
zarr = ">=2.18.3, <3"
dask = ">=2026.3.0, <2027"
napari = { version = ">=0.7.0, <0.8", extras = ["pyqt6"] }
scikit-image = ">=0.25.2, <0.26"
palom = { git = "https://github.com/labsyspharm/palom.git", rev = "ce611c8", extras = ["all"]}
shapely = ">=2.1.2, <3"
geojson = ">=3.2.0, <4"
ruff = ">=0.15.13, <0.16"